# Generated by Django 4.1.3 on 2022-11-27 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iptv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='channel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='guide', serialize=False, to='iptv.channel'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='bitrate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stream',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stream',
            name='width',
            field=models.IntegerField(),
        ),
    ]
