# Generated by Django 4.1.3 on 2022-11-27 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iptv', '0002_alter_guide_channel_alter_stream_bitrate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='country',
            new_name='countries',
        ),
    ]
