# Generated by Django 4.1.3 on 2022-11-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptv', '0003_rename_country_region_countries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='alt_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
