# Generated by Django 4.1.3 on 2022-11-27 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iptv', '0004_alter_channel_alt_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='channels', to='iptv.category'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='channels', to='iptv.country'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='languages',
            field=models.ManyToManyField(blank=True, null=True, related_name='channels', to='iptv.language'),
        ),
    ]
