# Generated by Django 4.1.3 on 2022-11-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptv', '0005_alter_channel_categories_alter_channel_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='categories',
            field=models.ManyToManyField(related_name='channels', to='iptv.category'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='languages',
            field=models.ManyToManyField(related_name='channels', to='iptv.language'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='added_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='http_referrer',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='user_agent',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
