# Generated by Django 4.1.3 on 2022-11-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptv', '0006_alter_channel_categories_alter_channel_languages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='bitrate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='frame_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
