# Generated by Django 4.1.3 on 2022-11-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptv', '0007_alter_stream_bitrate_alter_stream_frame_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='added_at',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='checked_at',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='updated_at',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
