# Generated by Django 4.1.3 on 2022-11-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptv', '0008_alter_stream_added_at_alter_stream_checked_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='added_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
