# Generated by Django 4.1.3 on 2022-11-27 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iptv', '0009_alter_stream_added_at_alter_stream_checked_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='streams', serialize=False, to='iptv.channel'),
        ),
    ]
