# Generated by Django 4.1.3 on 2022-11-27 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iptv', '0010_alter_stream_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stream',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='streams', to='iptv.channel'),
        ),
    ]
